[build]
dockerfilePath = "Dockerfile.backend"
watchPatterns = ["apps/backend/**", "pnpm-lock.yaml", "Dockerfile.backend"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "node ./src/scripts/cloud-start.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
