/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrescriptionPolicyRouteImport } from './routes/prescription-policy'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as PharmacyLicensesRouteImport } from './routes/pharmacy/licenses'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionPolicyRoute = PrescriptionPolicyRouteImport.update({
  id: '/prescription-policy',
  path: '/prescription-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const PharmacyLicensesRoute = PharmacyLicensesRouteImport.update({
  id: '/pharmacy/licenses',
  path: '/pharmacy/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/grievance': typeof GrievanceRoute
  '/health': typeof HealthRoute
  '/prescription-policy': typeof PrescriptionPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/pharmacy/licenses': typeof PharmacyLicensesRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/grievance': typeof GrievanceRoute
  '/health': typeof HealthRoute
  '/prescription-policy': typeof PrescriptionPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/pharmacy/licenses': typeof PharmacyLicensesRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/grievance': typeof GrievanceRoute
  '/health': typeof HealthRoute
  '/prescription-policy': typeof PrescriptionPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/pharmacy/licenses': typeof PharmacyLicensesRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/grievance'
    | '/health'
    | '/prescription-policy'
    | '/privacy'
    | '/returns'
    | '/store'
    | '/terms'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/pharmacy/licenses'
    | '/$countryCode/'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/grievance'
    | '/health'
    | '/prescription-policy'
    | '/privacy'
    | '/returns'
    | '/store'
    | '/terms'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/pharmacy/licenses'
    | '/$countryCode'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/grievance'
    | '/health'
    | '/prescription-policy'
    | '/privacy'
    | '/returns'
    | '/store'
    | '/terms'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/store'
    | '/pharmacy/licenses'
    | '/$countryCode/'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  GrievanceRoute: typeof GrievanceRoute
  HealthRoute: typeof HealthRoute
  PrescriptionPolicyRoute: typeof PrescriptionPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  PharmacyLicensesRoute: typeof PharmacyLicensesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription-policy': {
      id: '/prescription-policy'
      path: '/prescription-policy'
      fullPath: '/prescription-policy'
      preLoaderRoute: typeof PrescriptionPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/pharmacy/licenses': {
      id: '/pharmacy/licenses'
      path: '/pharmacy/licenses'
      fullPath: '/pharmacy/licenses'
      preLoaderRoute: typeof PharmacyLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}

interface CountryCodeRouteChildren {
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  GrievanceRoute: GrievanceRoute,
  HealthRoute: HealthRoute,
  PrescriptionPolicyRoute: PrescriptionPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  PharmacyLicensesRoute: PharmacyLicensesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
